export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const SET_PRODUCTS = "SET_PRODUCTS";
export const SET_SEARCH_PRODUCTS = "SET_SEARCH_PRODUCTS";
export const SEARCH_PRODUCTS = "SEARCH_PRODUCTS";
